# https://taskfile.dev

version: "3"

vars:
  IMAGE_NAME: hello-golang:latest

tasks:
  default:
    deps:
      - task: test

  test:
    cmds:
      - go test -v ./{{.CLI_ARGS | default "..."}}

  docker-build:
    cmds:
      - docker buildx build --tag {{.IMAGE_NAME}} .

  docker-bash:
    cmds:
      - docker run -it --rm -v ${PWD}:/go/src/app {{.IMAGE_NAME}} bash

  docker-zsh:
    cmds:
      - docker run -it --rm -v ${PWD}:/go/src/app {{.IMAGE_NAME}} zsh

  docker-test:
    cmds:
      - docker run --rm -v ${PWD}:/go/src/app {{.IMAGE_NAME}} go test -v ./{{.CLI_ARGS | default "..."}}

  docker-build-test:
    cmds:
      - task: docker-build
      - task: docker-test

  docker-prune:
    cmds:
      - docker system prune -f
