# https://taskfile.dev

version: "3"

vars:
  IMAGE_NAME: hello-golang:latest

tasks:
  default:
    deps:
      - task: test

  test:
    desc: Execute testing via local golang binary
    cmds:
      - go test -v ./{{.CLI_ARGS | default "..."}}
    silent: true

  marp:
    cmds:
      - docker run --rm -v $PWD/assets/marp:/home/marp/app/ -e MARP_USER="$(id -u):$(id -g)" -e LANG=$LANG marpteam/marp-cli --html true {{.CLI_ARGS}}
      - mv $PWD/assets/marp/$(echo {{.CLI_ARGS}} | awk -F . '{print $1".html"}') $PWD/docs/marp/
      - cp -r $PWD/assets/marp/img $PWD/docs/marp/
    silent: true
