name: Testing Chapter 03

on:
  workflow_dispatch:
  push:
    paths:
      - "subject/chapter03/**.go"

env:
  TARGET: chapter03

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Go Test
        run: go test -v ./subject/${TARGET}
