<<<<<<<< HEAD:.github/workflows/chapter00_test.yml
name: Testing Chapter 00
========
name: Testing Chapter 01
>>>>>>>> e98c5f1 (第1回の課題を実装 (#18)):.github/workflows/chapter01_test.yml

on:
  workflow_dispatch:
  push:
    paths:
<<<<<<<< HEAD:.github/workflows/chapter00_test.yml
      - "subject/chapter00/**.go"

env:
  TARGET: chapter00
========
      - "subject/chapter01/**.go"

env:
  TARGET: chapter01
>>>>>>>> e98c5f1 (第1回の課題を実装 (#18)):.github/workflows/chapter01_test.yml

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Go Test
<<<<<<<< HEAD:.github/workflows/chapter00_test.yml
        run: go test -v ./subject/${TARGET}
========
        run: go test -v ./subject/${TARGET}
>>>>>>>> e98c5f1 (第1回の課題を実装 (#18)):.github/workflows/chapter01_test.yml
