name: Testing Chapter 03

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths:
      - "subject/chapter03/**.go"

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: './.github/actions/test'
        with:
          target: chapter03
